SELECT /*+ first_rows(50) */ *
FROM	(SELECT PAGING.*,
	ROW_NUMBER() OVER(ORDER BY FRAMEWORK_ORDER_INDEX) PAGING_RN
FROM	(SELECT RETURNED_ROWS.*,
	NULL FRAMEWORK_ORDER_INDEX
FROM	(SELECT SUMMARIZER.* ,
	COUNT(1) OVER() QT_TOT_REG_INT_WCP
FROM	(
    --SEPARANDO:
    SELECT   
     nm_paciente,
	 ds_status_analise,
	 ie_reconciliacao,
	 ds_unidade,
	 ds_unidade_basica,
	 ds_unidade_comp,
	 ds_itens_pendentes as ds_novos_itens,
	 dt_alta,
	 dt_atendimento,
	 dt_prox_adm,
	 nr_atendimento,
	 cd_pessoa_fisica,
	 dt_alta_medico,
	 ie_forma_reconciliacao,
	 nr_prontuario,
	 qt_peso,
	 qt_altura,
	 ds_setor_atendimento,
	 ds_setor_atual,
	 ie_emergencia,
	 ie_urgente,
	 nr_seq_cor,
	 nr_cor_idade,
	 ie_analise_ativa,
	 ie_analise_item_ativa,
	 ie_item_bloqueado,
	 dt_inicio_analise,
	 dt_fim_analise,
	 nm_compl_resp_analise,
	 nm_usuario_analise,
	 dt_inicio_analise_enf,
	 dt_fim_analise_enf,
	 nm_compl_resp_analise_enf,
	 nm_resp_analise_enf,
	 dt_inicio_analise_farm,
	 dt_fim_analise_farm,
	 nm_compl_resp_analise_farm,
	 nm_resp_analise_farm ,
	 nr_ultima_prescr,
	 nm_usuario_anal_enf,
	 dt_inicio_anal_enf,
	 ie_possui_prescricao,
	 obter_profissional_atend(nr_atendimento,
	'E',
	'N') as cd_lead_nurse,
	 obter_nome_departamento_medico(obter_departamento_atual_atend(nr_atendimento)) as cd_medical_department,
	 decode(null,
	null,
	'0',
	obter_ult_resultado_lab(cd_pessoa_fisica,
	null)) as valor_creatinina,
	 null as nursing_team,
	 null as estimated_date,
	 ds_observacoes_pac
FROM	 table(gpt_utils_pck.get_pending_patients(   null,
	  null,
	  null,
	  --to_date('27/11/2024 00:00:00',	'dd/mm/yyyy hh24:mi:ss'),
	  --to_date('28/11/2024 23:59:59',	'dd/mm/yyyy hh24:mi:ss'),
      SYSDATE - 1 ,
      SYSDATE,
	  null,
	  '1',
	  null,
	  null,
	  null,
	  null,
	  null,
	  null,
	  'N',
	  'N',
	  2,
	  'N',
	  'A',
	  'N',
	  null,
	  'S',
	  1,
	  2,
	  'N',
	  'N',
	  null,
	  'N',
	  'E',
	  'N',
	  'N',
	  2,
	  'N',
	  'N',
	  'A',
	  'T',
	  'N',
	  'T',
	  'E',
	  null,
	  2,
	  'N',
	  'S',
	  'acmmeireles',
	  null,
	  0,
	  '15',
	  null,
	  'N',
	  null,
	  null,
	  null  )) 
WHERE 1 = 1
ORDER BY obter_prim_prescr_mat_hor_gpt(nr_atendimento, cd_pessoa_fisica, 'acmmeireles', '1')

) SUMMARIZER) RETURNED_ROWS) PAGING)
WHERE (PAGING_RN >= 1) 
	AND	(PAGING_RN < 51)