Time -> 807ms 

SELECT /*+ first_rows(50) */ *
FROM	(SELECT PAGING.*,
	ROW_NUMBER() OVER(ORDER BY FRAMEWORK_ORDER_INDEX) PAGING_RN
FROM	(SELECT RETURNED_ROWS.*,
	NULL FRAMEWORK_ORDER_INDEX
FROM	(SELECT SUMMARIZER.* ,
	COUNT(1) OVER() QT_TOT_REG_INT_WCP
FROM	(SELECT   nm_paciente,
	ds_status_analise,
	 ie_reconciliacao,
	 ds_unidade,
	 ds_unidade_basica,
	 ds_unidade_comp,
	 ds_itens_pendentes as ds_novos_itens,
	 dt_alta,
	 dt_atendimento,
	 dt_prox_adm,
	 nr_atendimento,
	 cd_pessoa_fisica,
	 dt_alta_medico,
	 ie_forma_reconciliacao,
	 nr_prontuario,
	 qt_peso,
	 qt_altura,
	 ds_setor_atendimento,
	 ds_setor_atual,
	 ie_emergencia,
	 ie_urgente,
	 nr_seq_cor,
	 nr_cor_idade,
	 ie_analise_ativa,
	 ie_analise_item_ativa,
	 ie_item_bloqueado,
	 dt_inicio_analise,
	 dt_fim_analise,
	 nm_compl_resp_analise,
	 nm_usuario_analise,
	 dt_inicio_analise_enf,
	 dt_fim_analise_enf,
	 nm_compl_resp_analise_enf,
	 nm_resp_analise_enf,
	 dt_inicio_analise_farm,
	 dt_fim_analise_farm,
	 nm_compl_resp_analise_farm,
	 nm_resp_analise_farm ,
	nr_ultima_prescr,
	 nm_usuario_anal_enf,
	 dt_inicio_anal_enf,
	 ie_possui_prescricao,
	 obter_profissional_atend(nr_atendimento,
	'E',
	'N') as cd_lead_nurse,
	 obter_nome_departamento_medico(obter_departamento_atual_atend(nr_atendimento)) as cd_medical_department,
	 decode(:vl_param68,
	null,
	'0',
	obter_ult_resultado_lab(cd_pessoa_fisica,
	:vl_param68)) as valor_creatinina,
	 null as nursing_team,
	 null as estimated_date,
	 ds_observacoes_pac
FROM	 table(gpt_utils_pck.get_pending_patients(   :nr_atendimento,
	  :cd_pessoa_fisica,
	  :nr_prescricao,
	  :dt_inicial,
	  :dt_final,
	  :cd_classe_material,
	  :cd_estabelecimento,
	  :cd_grupo_material,
	  :cd_intervalo,
	  :cd_material,
	  :cd_setor_atend,
	  :cd_subgrupo_material,
	  :ie_Classif_setor_exibe,
	  :ie_alta_vigilancia,
	  :ie_alto_risco,
	  :ie_dispensacao,
	  :ie_exibe_alta,
	  :ie_intervencao_farm,
	  :ie_item_farm_nao_atend,
	  :ie_itens,
	  :ie_lib_farm,
	  :ie_liberacao_enf,
	  :ie_liberacao_farm,
	  :ie_medic_alto_custo,
	  :ie_medic_paciente,
	  :ie_motivo_prescricao,
	  :ie_nao_padronizado,
	  :ie_param_1,
	  :ie_param_91,
	  :ie_param_92,
	  :ie_prescritor,
	  :ie_quimio,
	  :ie_restrito,
	  :ie_revisado,
	  :ie_revisao,
	  :ie_sem_atendimento,
	  :ie_status_farm,
	  :ie_tipo_gpt,
	  :ie_tipo_item,
	  :ie_urgencia,
	  :ie_vaga_solicitada,
	  :ie_vigentes,
	  :nm_usuario,
	  :nr_seq_classif_transcr,
	  :qt_horas_quimio,
	  :qt_minutos_agora,
	  :fa_complementos,
	  :ie_antibiotico,
	  :fa_setor,
	  :fa_motivos,
	  :fa_matmeds  )) 
WHERE 1 = 1
ORDER BY obter_prim_prescr_mat_hor_gpt(nr_atendimento, cd_pessoa_fisica, :nm_usuario, :cd_estabelecimento)) SUMMARIZER) RETURNED_ROWS) PAGING)
WHERE (PAGING_RN >= 1) 
	AND	(PAGING_RN < 51)